"""Canonical operational defaults for PM Copilot runtimes.

These are code-owned policy defaults, not deployment configuration. Existing
callers can still override them through their current CLI/API arguments.
"""

from __future__ import annotations

DEFAULT_EXECUTION_TIMEOUT_MINUTES = 15
# Aggregate budget for a confirmed delivery; distinct from one Agent call.
DEFAULT_INTERACTIVE_TIMEOUT_MINUTES = 60
DEFAULT_INTERACTIVE_MAX_REVISIONS = 3
DEFAULT_EVALUATION_MAX_REVISIONS = 2
DEFAULT_PORTFOLIO_MAX_REVISIONS = 1
DEFAULT_PORTFOLIO_WORKERS = 1
MAX_CODEX_CASE_WORKERS = 3
DEFAULT_LOOP_TIMEOUT_MINUTES = 30
DEFAULT_LOOP_MAX_ITERATIONS = 2
SEAWORK_RESTART_TIMEOUT_SECONDS = 90

__all__ = [
    "DEFAULT_EVALUATION_MAX_REVISIONS", "DEFAULT_EXECUTION_TIMEOUT_MINUTES",
    "DEFAULT_INTERACTIVE_TIMEOUT_MINUTES",
    "DEFAULT_INTERACTIVE_MAX_REVISIONS", "DEFAULT_LOOP_MAX_ITERATIONS",
    "DEFAULT_LOOP_TIMEOUT_MINUTES", "DEFAULT_PORTFOLIO_MAX_REVISIONS",
    "DEFAULT_PORTFOLIO_WORKERS", "MAX_CODEX_CASE_WORKERS",
    "SEAWORK_RESTART_TIMEOUT_SECONDS",
]
